import { readdir, stat } from "node:fs/promises";
import { join, basename, relative } from "node:path";

const ROOT = import.meta.dir;
const SRC_DIR = join(ROOT, "src");

/** Format a Date as ISO 8601 with local timezone offset (e.g. +09:00). */
function formatLocalISO(date: Date): string {
  const off = -date.getTimezoneOffset();
  const sign = off >= 0 ? "+" : "-";
  const absOff = Math.abs(off);
  const hh = String(Math.floor(absOff / 60)).padStart(2, "0");
  const mm = String(absOff % 60).padStart(2, "0");
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` +
    `T${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}` +
    `${sign}${hh}:${mm}`
  );
}

interface PostInfo {
  /** Filename without the .typ suffix */
  id: string;
  /** Absolute path to the source file */
  path: string;
  /** ISO 8601 creation timestamp */
  createdAt: string;
  /** ISO 8601 last-modification timestamp */
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Run a command and return its trimmed stdout. */
async function exec(cmd: string[]): Promise<string> {
  const proc = Bun.spawn(cmd, {
    cwd: ROOT,
    stdout: "pipe",
    stderr: "pipe",
  });
  const output = await new Response(proc.stdout).text();
  await proc.exited;
  return output.trim();
}

/**
 * Query git log for author-date timestamps of every commit that touched
 * `filePath`.  Returns the oldest (created) and newest (updated) dates, or
 * undefined when the file has no git history yet.
 */
async function getGitDates(
  filePath: string,
): Promise<{ created?: string; updated?: string }> {
  const relPath = relative(ROOT, filePath);

  // --follow tracks renames; %aI = strict ISO 8601 author date
  const log = await exec([
    "git",
    "log",
    "--format=%aI",
    "--follow",
    "--",
    relPath,
  ]);

  if (!log) return {};

  const dates = log.split("\n").filter(Boolean);
  return {
    created: dates[dates.length - 1], // oldest commit
    updated: dates[0], // most recent commit
  };
}

/**
 * Return `true` when the working-tree copy of `filePath` differs from what
 * git knows about (unstaged modifications, staged-but-uncommitted changes,
 * or the file being completely untracked).
 */
async function hasUncommittedChanges(filePath: string): Promise<boolean> {
  const relPath = relative(ROOT, filePath);
  const status = await exec([
    "git",
    "status",
    "--porcelain",
    "--",
    relPath,
  ]);
  return status.length > 0;
}

// ---------------------------------------------------------------------------
// Per-post metadata
// ---------------------------------------------------------------------------

async function getPostInfo(filePath: string): Promise<PostInfo> {
  const id = basename(filePath, ".typ");
  const [gitDates, uncommitted, fileStat] = await Promise.all([
    getGitDates(filePath),
    hasUncommittedChanges(filePath),
    stat(filePath),
  ]);
  const mtime = formatLocalISO(fileStat.mtime);

  // Creation time: first git commit that introduced the file, or mtime if
  // the file has never been committed.
  const createdAt = gitDates.created ?? mtime;

  // Modification time: if the working-tree copy has uncommitted changes (or
  // the file is untracked), fall back to the filesystem mtime.
  const updatedAt = uncommitted || !gitDates.updated ? mtime : gitDates.updated;

  return { id, path: filePath, createdAt, updatedAt };
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function escapeTypstString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function generatePostsTyp(posts: PostInfo[], commitHash: string): string {
  const lines: string[] = [
    "// Auto-generated by build.ts \u2014 do not edit manually",
    "",
    `#import \"common.typ\": scribble-hash, scribble-id, scribble-created, scribble-updated`,
    "",
    `#scribble-hash.update("${escapeTypstString(commitHash)}")`,
    "",
  ];

  for (const post of posts) {
    const relPath = relative(ROOT, post.path);
    const eid = escapeTypstString(post.id);
    const eca = escapeTypstString(post.createdAt);
    const eua = escapeTypstString(post.updatedAt);

    lines.push(`#scribble-id.update("${eid}")`);
    lines.push(`#scribble-created.update("${eca}")`);
    lines.push(`#scribble-updated.update("${eua}")`);
    lines.push(``);
    lines.push(`#include "${relPath}"`);
    lines.push(``);
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const [entries, commitHash] = await Promise.all([
    readdir(SRC_DIR),
    exec(["git", "rev-parse", "HEAD"]),
  ]);
  const typFiles = entries
    .filter((f) => f.endsWith(".typ"))
    .map((f) => join(SRC_DIR, f));

  if (typFiles.length === 0) {
    console.log("No .typ files found in src/");
    return;
  }

  // Gather metadata in parallel
  const posts = await Promise.all(typFiles.map(getPostInfo));

  // Sort by decreasing modification time (most recently updated first)
  posts.sort(
    (a, b) =>
      new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
  );

  // Write posts.typ
  const outputPath = join(ROOT, "posts.typ");
  await Bun.write(outputPath, generatePostsTyp(posts, commitHash));

  console.log(`Generated ${outputPath} with ${posts.length} post(s):`);
  for (const post of posts) {
    console.log(
      `  - ${post.id}  (created: ${post.createdAt}, updated: ${post.updatedAt})`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
